package com.improve.trading.strategy.commons.arbitrage;

public enum Index {

    DEFI_LAG(true),
    DEFI_LEAD(false),
    PRIVACY_LAG(true),
    PRIVACY_LEAD(false),
    NFT_LAG(true),
    NFT_LEAD(false),
    MATH1_LAG(true),
    MATH1_LEAD(false),
    MATH2_LAG(true),
    MATH2_LEAD(false),
    // MATH3_LAG(true),
    // MATH3_LEAD(false),
    // MATH4_LAG(true),
    // MATH4_LEAD(false),
    // MATH5_LAG(true),
    // MATH5_LEAD(false),
    MATH6_LAG(true),
    MATH6_LEAD(false),
    MATH7_LAG(true),
    MATH7_LEAD(false),
    MATH8_LAG(true),
    MATH8_LEAD(false),
    // MATH9_LAG(true),
    // MATH9_LEAD(false),
    MATH10_LAG(true),
    MATH10_LEAD(false),
    MATH11_LAG(true),
    MATH11_LEAD(false),
    MATH12_LAG(true),
    MATH12_LEAD(false),
    // MATH13_LAG(true),
    // MATH13_LEAD(false),
    // MATH14_LAG(true),
    // MATH14_LEAD(false),
    // MATH15_LAG(true),
    // MATH15_LEAD(false),
    // MATH16_LAG(true),
    // MATH16_LEAD(false),
    // MATH17_LAG(true),
    // MATH17_LEAD(false),
    MATH18_LAG(true),
    MATH18_LEAD(false),
    MATH19_LAG(true),
    MATH19_LEAD(false),
    MATH20_LAG(true),
    MATH20_LEAD(false),
    MATH21_LAG(true),
    MATH21_LEAD(false),
    MATH22_LAG(true),
    MATH22_LEAD(false),
    MATH23_LAG(true),
    MATH23_LEAD(false),
    MATH24_LAG(true),
    MATH24_LEAD(false),
    MATH25_LAG(true),
    MATH25_LEAD(false),
    MATH26_LAG(true),
    MATH26_LEAD(false),
    MATH27_LAG(true),
    MATH27_LEAD(false),
    MATH28_LAG(true),
    MATH28_LEAD(false),
    MATH29_LAG(true),
    MATH29_LEAD(false),
    MATH30_LAG(true),
    MATH30_LEAD(false),
    MATH31_LAG(true),
    MATH31_LEAD(false),
    MATH32_LAG(true),
    MATH32_LEAD(false),
    MATH33_LAG(true),
    MATH33_LEAD(false),
    MATH34_LAG(true),
    MATH34_LEAD(false),
    MATH35_LAG(true),
    MATH35_LEAD(false),
    MATH36_LAG(true),
    MATH36_LEAD(false),
    MATH37_LAG(true),
    MATH37_LEAD(false),
    MATH38_LAG(true),
    MATH38_LEAD(false),
    MATH39_LAG(true),
    MATH39_LEAD(false),
    MATH40_LAG(true),
    MATH40_LEAD(false),

    NMATH0_LAG(true),
    NMATH0_LEAD(false),
    NMATH1_LAG(true),
    NMATH1_LEAD(false),
    NMATH2_LAG(true),
    NMATH2_LEAD(false),
    NMATH3_LAG(true),
    NMATH3_LEAD(false),
    NMATH4_LAG(true),
    NMATH4_LEAD(false),
    NMATH5_LAG(true),
    NMATH5_LEAD(false),
    NMATH6_LAG(true),
    NMATH6_LEAD(false),
    NMATH7_LAG(true),
    NMATH7_LEAD(false),
    NMATH8_LAG(true),
    NMATH8_LEAD(false),
    NMATH9_LAG(true),
    NMATH9_LEAD(false),

    

    UNKNOWN(false);

    public boolean isLag;

    Index(boolean isMaster) {
        this.isLag = isMaster;
    }

}
